name: ESP Lint

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

env:
  IMAGE_DEFAULT: ghcr.io/sivakov512/esp-idf:v5.5.3-llvm19
  IMAGE_MATTER: ghcr.io/sivakov512/esp-matter:release_v1.5-idf_v5.5.3-llvm19

jobs:
  detect:
    runs-on: ubuntu-latest
    outputs:
      container: ${{ steps.pick.outputs.container }}
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Pick container image
        id: pick
        run: |
          if grep -qP 'set\(ESP_MATTER_ENABLED\s+true\)' CMakeLists.txt; then
            echo "container=${{ env.IMAGE_MATTER }}" >> "$GITHUB_OUTPUT"
          else
            echo "container=${{ env.IMAGE_DEFAULT }}" >> "$GITHUB_OUTPUT"
          fi

  lint:
    needs: detect
    runs-on: ubuntu-latest
    container:
      image: ${{ needs.detect.outputs.container }}
    defaults:
      run:
        shell: bash

    steps:
      - name: Get container image digest
        run: |
          curl -fsSL https://github.com/google/go-containerregistry/releases/latest/download/go-containerregistry_Linux_x86_64.tar.gz | tar -xz crane
          echo "DIGEST=$(./crane digest ${{ needs.detect.outputs.container }})" >> $GITHUB_ENV

      - name: Checkout
        uses: actions/checkout@v4
        with:
          submodules: recursive

      - name: Init ESP-IDF envirornment
        run: |
          cat > "$GITHUB_WORKSPACE/.bash_env_ci" <<'EOF'
          # guard to avoid re-sourcing on every nested bash
          if [ -z "${__ESP_IDF_SOURCED__:-}" ]; then
            export __ESP_IDF_SOURCED__=1
            source /opt/esp/entrypoint.sh
          fi
          EOF
          echo "BASH_ENV=$GITHUB_WORKSPACE/.bash_env_ci" >> "$GITHUB_ENV"

      - name: Cache build artefacts
        uses: actions/cache@v3
        with:
          path: |
            build
            managed_components
          key: ${{ runner.os }}-${{ env.DIGEST }}-esp-lint-${{ hashFiles('**/CMakeLists.txt', 'sdkconfig.defaults', 'main/idf_component.yml') }}
          restore-keys: |
            ${{ runner.os }}-${{ env.DIGEST }}-esp-lint-

      - name: Build project
        run: make esp-build

      - name: Run static analysis
        run: make esp-lint
